name: sd
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - numpy
  - pip:
      - albumentations
      - diffusers
      - opencv-python
      - pudb
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning
      - omegaconf
      - streamlit
      - einops
      - torch-fidelity
      - transformers
      - torchmetrics
      - kornia
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e .
