model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 8 # real_image_size / 2 ** len(ch_mult): 2**3      e.g. 192 / 8 = 24
    channels: 8
    cond_stage_trainable: false
    conditioning_key: "crossattn"
    scale_by_std: True
    monitor: 'val/loss_simple_ema'
    use_positional_encodings: False
    use_ema: false

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 512
        image_size: 8
        in_channels: 8
        out_channels: 8
        model_channels: 128
        attention_resolutions: [ 2,4,8 ]
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4 ]
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 8
        ckpt_path: "/home/luo/repo/stable-diffusion/logs/2024-05-26T15-59-44_vae/checkpoints/last.ckpt"
        ddconfig:
          double_z: True
          z_channels: 8
          resolution: 128
          in_channels: 3
          out_ch: 3
          ch: 32
          ch_mult: [ 1,2,2,4,4 ]  # num_down = len(ch_mult)-1
          # output feature map size 8
          num_res_blocks: 2
          attn_resolutions: [ 8,16 ]
          dropout: 0.0
        lossconfig:
          target:
            torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.CLIPReIDEmbedder
      params:
        clip_ckpt_path: "/home/luo/repo/stable-diffusion/logs/2024-04-24T12-12-56_clip_all/checkpoints/last.ckpt"

data:
  target: main.DataModuleFromConfig
  params:
    # change bs in get_input of DDPM as well
    batch_size: 128
    num_workers: 23
    wrap: True
    train:
      target: ldm.data.reid.UniPedTrainAll
      params:
        size: 128
    validation:
      target: ldm.data.reid.UniPedValidation
      params:
        size: 128
    test:
      target: ldm.data.reid.UniPedTest
      params:
        size: 128

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000000
        max_images: 8
        increase_log_steps: false

  trainer:
    max_epochs: 1000