model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "caption"
    image_size: 24 # real_image_size / 2 ** len(ch_mult): 2**3      e.g. 192 / 8 = 24
    channels: 4
    cond_stage_trainable: false
    conditioning_key: "crossattn"
    scale_by_std: True
    monitor: 'val/loss_simple_ema'
    use_positional_encodings: False
    use_ema: false

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 512
        image_size: 24
        in_channels: 4
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 2,4,8 ]
        num_res_blocks: 2
        channel_mult: [ 1,2,3,4 ]
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ckpt_path: "/home/luo/repo/stable-diffusion/logs/2024-04-29T10-10-03_vae/checkpoints/epoch=000009.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 192
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ 24 ]
          dropout: 0.0
        lossconfig:
          target:
            torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.CLIPReIDEmbedder
      params:
        clip_ckpt_path: "/home/luo/repo/stable-diffusion/logs/2024-04-24T12-12-56_clip_all/checkpoints/last.ckpt"